JO FILES COPY KRENGE CREDIT DE DE NA ğŸ‘ğŸ»

WORKING ON
GITLAB & BITBUCKET & VPS âœ… 

COMMANDS ğŸ‘‡ğŸ»

chmod +x *
gcc -o bgmi arman.c -lpthread
pip install telebot
pip install flask
pip install aiogram
chmod +x *
chmod +x bgmi
./bgmi
python3 arman.py

GITLAB COMMANDS FILE ğŸ‘‡ğŸ»

FILE NAME ğŸ‘‡ğŸ»
.gitlab-ci.yml
_

stages:
  - setup
  - run

setup_environment:
  stage: setup
  image: python:3.9
  script:
    - echo "done join @ARMANTEAMVIP"

run_script:
  stage: run
  image: python:3.9
  dependencies:
    - setup_environment
  script:
    - pip install telebot flask aiogram python-telegram-bot pymongo  && gcc -o bgmi arman.c -lpthread && chmod +x * && python arman.py

restart_pipeline:
  stage: run
  image: python:3.9
  script:
    - echo "Sleeping for 1 hour before restarting..."
    - sleep 3600
    - echo "Restarting the pipeline..."
    - curl -X POST -F token=$CI_JOB_TOKEN -F ref=$CI_COMMIT_REF_NAME https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline
  only:
    - main  # Adjust if using a different branch


BITBUCKET COMMANDS

FILE NAME ğŸ‘‡ğŸ» 
bitbucket-pipelines.yml
____

pipelines:
  default:
    - step:
        name: Run Python Script
        image: python:3.10
        script:
          - echo "Starting pipeline..."

          - pip install telebot pymongo aiohttp && gcc -o bgmi arman.c -lpthread && chmod +x * && python3 arman.py
